Updated mode picker to use collection view
skedgo/tripkit-ios pull request #123
Opened 2021-11-19 01:58 UTC by pnuts2

Closes RM15993

2021-11-20 21:04 UTC, nighthawk approved these changes
Looks good to me, just some minor comments.

2021-11-20 21:04 UTC, nighthawk commented on Sources/TripKitUI/views/TKUIModePicker.swift
> +    collectionView.showsHorizontalScrollIndicator = false
I vaguely recall that there's a way to disable scrolling completely on a collection view (or scroll view?) and that wouldn't be necessary then.

2021-11-20 21:04 UTC, nighthawk commented on Sources/TripKitUI/views/TKUIModePickerCell.swift
> +    rightImageView.layer.cornerRadius = rightImageView.frame.width * 0.5
Can this cell resize? If so, you might need to do the same as also on `didSet` of the frame.

2021-11-22 01:35 UTC, nighthawk commented
@pnuts2 Tried this in TripGo in Sydney, but something is broken:

![PNG image](https://user-images.githubusercontent.com/22646/142788575-d98b68ab-631b-4f1d-9a60-11bc9b200bb4.png)

2021-11-22 01:37 UTC, pnuts2 commented
> @pnuts2 Tried this in TripGo in Sydney, but something is broken:
> 
> ![PNG image](https://user-images.githubusercontent.com/22646/142788575-d98b68ab-631b-4f1d-9a60-11bc9b200bb4.png)

Yes, I've seen that previously, and thought I have fixed it. Will take a look at this again once I wrapped up the Feonix work on converting from button press to cell tap

2021-11-22 03:33 UTC, nighthawk requested changes
See bug/screenshot from the conversation. Brian is on it.

2021-11-22 04:36 UTC, nighthawk approved these changes
Works after all after I updated TripGo. Sorry for the confusion.

2021-11-22 04:45 UTC, merged